name: Setup Environment

inputs:
  package_manager:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install dependencies for extraction
      if: inputs.package_manager == 'apt'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev libudev-dev

    - name: Download libevdev-dev package
      shell: bash
      run: |
        mkdir -p libevdev_pkg
        cd libevdev_pkg
        apt-get download libevdev-dev

    - name: Extract libevdev-dev package
      shell: bash
      run: |
        cd libevdev_pkg
        dpkg-deb -x *.deb extracted_libevdev

    - name: Move files to appropriate directories
      shell: bash
      run: |
        sudo cp -r libevdev_pkg/extracted_libevdev/usr/include/libevdev-1.0/* /usr/local/include/
        sudo cp -r libevdev_pkg/extracted_libevdev/usr/lib/* /lib/
        sudo ldconfig
