name: Build and Test

on:
  - push
  - pull_request

jobs:
  build:

    strategy:
      matrix:
        os:
          - name: ubuntu-beta
            runs-on: ubuntu-24.04
            package_manager: apt
          - name: ubuntu-latest
            runs-on: ubuntu-latest
            package_manager: apt
          - name: ubuntu-old
            runs-on: ubuntu-20.04
            package_manager: apt
    runs-on: ${{ matrix.os['runs-on'] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          package_manager: ${{ matrix.os.package_manager }}

      - name: Compile C++ code
        shell: bash
        run: |
          g++ -std=c++17 -o ProtonTPR src/ProtonTPR.cpp -I/usr/local/include/libevdev-1.0 -L/lib -levdev -ludev
          echo "Compilation finished successfully."

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProtonTPR-binary-${{ matrix.os.name }}
          path: ./ProtonTPR
